
spring:
  datasource:
    url: jdbc:mysql://47.103.10.220/db_joinblog?autoReconnect=true&useSSL=false&characterEncoding=utf-8&&serverTimezone=UTC
    username: root
    password: Join666
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    username: root
#    password: 123ljx456
#    url: jdbc:mysql://localhost:3306/db_joinblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.join.joinblog.entity


logging:
  level:
   com:
     join:
       joinblog:
         mapper: debug
